# Generated by Django 5.1.4 on 2024-12-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakiapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
