# Generated by Django 5.1.4 on 2025-01-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakiapi', '0004_alter_order_options_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paiement_method',
            field=models.CharField(choices=[('A la livraison', 'A la livraison'), ('wave', 'wave')], default='A la livraison', max_length=20),
        ),
    ]
