# Generated by Django 5.1.4 on 2025-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakiapi', '0007_order_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paiement_method',
            field=models.CharField(choices=[('A la livraison', 'A la livraison'), ('wave', 'wave'), ('Orange Money', 'Orange Money'), ('Moov Money', 'Moov Money'), ('Moov money', 'Moov money')], default='A la livraison', max_length=20),
        ),
    ]
