# Generated by Django 5.1.4 on 2025-01-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakiapi', '0008_order_invoice_number_alter_order_paiement_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paiement_method',
            field=models.CharField(choices=[('A la livraison', 'A la livraison'), ('wave', 'wave'), ('Orange Money', 'Orange Money'), ('Mtn Money', 'Mtn Money'), ('Moov money', 'Moov money')], default='A la livraison', max_length=20),
        ),
    ]
