POST http://127.0.0.1:8000/zakiapi/orders/create/
Content-Type: application/json

{
    "user": "3",
    "product": "1",
    "total_price": 10000,
    "paiement_method": "wave",
    "status": "pending"
}
